export default {
  id: "genericApp",
  name: "Generic App",
  description: "A simple multi-file Next.js app generated by Astrion",

  variables: {
    appName: "Generic App",
    primaryColor: "#0f172a"
  },

  requiredVariables: ["appName"],

  presets: [
    {
      id: "dark",
      name: "Dark App",
      variables: {
        primaryColor: "#020617"
      }
    },
    {
      id: "green",
      name: "Green Startup",
      variables: {
        primaryColor: "#22c55e"
      }
    }
  ],

  files: {
    "app/page.tsx": `
export default function Page() {
  return (
    <main style={{ padding: 40 }}>
      <h1>{{appName}}</h1>
      <p>This app was generated by Astrion.</p>
    </main>
  );
}
`,
    "app/layout.tsx": `
export default function RootLayout({ children }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
`,
    "app/globals.css": `
body {
  margin: 0;
  font-family: system-ui, sans-serif;
  background-color: {{primaryColor}};
}
`,
    "README.md": `
# {{appName}}

Generated by Astrion.
`
  }
};
